### ISSUE TITLE
reproduce results

### ISSUE THREAD

**Issue by stillwalker1234** [AI4Science-WestlakeU/beno#1]
Hi,

Wanted to try and reproduce the results of the paper, but `analysis.py` imports `RandomMeshGenerator` which does not exist anywhere.

Can you help me with the steps the to reproduce results of the paper?

@tailintalent @WillDreamer 

thanks in advance

**Comment by Seventy-eleven** [comment]
Hi,

I  also encountered an issue when running `analysis.py`. It tries to use `RandomMeshGenerator`, but this class or function is not defined anywhere in the project. 

Could you please clarify if `RandomMeshGenerator` was removed or if there is a missing file? 
Thanks in advance!

**Comment by WillDreamer** [comment]
Thanks for your reminder. We have updated `RandomMeshGenerator` in `utilities.py`.
